type: object
required:
    - documento_madre
    - documento_padre
    - minore
properties:
    madre:
        $ref: "definitions.yaml#/schemas/Person"
    documento_madre:
        $ref: "definitions.yaml#/schemas/IdentityDocument"
    documento_padre:
        $ref: "definitions.yaml#/schemas/IdentityDocument"
    padre:
        $ref: "definitions.yaml#/schemas/Person"
    minore:
        $ref: "definitions.yaml#/schemas/Person"
    podesta:
        oneOf:
        - type: string
          title: congiunta
          const: congiunta
        - type: object
          title: esclusiva
          properties:
            atto:
                $ref: "definitions.yaml#/schemas/IdentityDocument"
    contatti:
        type: array
        minItems: 1
        items:
            properties:
                cellulare:
                    type: string
