type: object
required:
    - richiedente_sottoscritto
    - richiedente
properties:
    destinatario:
        type: string
        default: Al signor Sindaco del Comune di Bugliano
    richiedente:
        $ref: "definitions.yaml#/schemas/Person"
    obblighi_scolastici:
        type: string
        enum:
            - licenza elementare
            - licenza media

    